# Generated by Django 4.1.6 on 2023-02-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('gender', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('Branch', models.CharField(max_length=100)),
                ('account', models.TextField()),
                ('materials', models.TextField()),
            ],
        ),
    ]
