# Generated by Django 4.1.6 on 2023-02-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_department_employee_remove_branch_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deptid',
        ),
        migrations.DeleteModel(
            name='department',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
