# Generated by Django 4.1.6 on 2023-02-12 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Branch',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
        migrations.AddField(
            model_name='person',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
