# Generated by Django 4.1.6 on 2023-02-12 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0006_rename_city_branch_rename_country_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 2, 6, 52, 924916), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
