# Generated by Django 4.1.6 on 2023-02-12 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0007_alter_person_dob_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 2, 37, 35, 518958), null=True),
        ),
    ]
