# Generated by Django 4.1.6 on 2023-02-12 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0010_rename_district_branch_country_alter_person_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 3, 1, 59, 848033), null=True),
        ),
    ]
