# Generated by Django 4.1.6 on 2023-02-12 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0013_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 3, 48, 24, 526268), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='materials',
            field=models.BooleanField(default=True),
        ),
    ]
