# Generated by Django 4.1.6 on 2023-02-12 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0014_alter_person_dob_alter_person_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='materials',
            new_name='check_book',
        ),
        migrations.AddField(
            model_name='person',
            name='credit_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='debit_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pass_book',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 4, 0, 26, 983455), null=True),
        ),
    ]
