# Generated by Django 4.1.6 on 2023-02-12 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0015_rename_materials_person_check_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('depoit', 'Depoit'), ('demat', 'Demat')], default='Debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 4, 49, 9, 54442), null=True),
        ),
    ]
