# Generated by Django 4.1.6 on 2023-02-13 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0016_alter_person_account_type_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 6, 29, 0, 645148), null=True),
        ),
    ]
