# Generated by Django 4.1.6 on 2023-02-13 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0017_alter_person_address_alter_person_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('depoit', 'Depoit'), ('demat', 'Demat')], default='----', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='check_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='debit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 13, 17, 59, 18, 367149), null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pass_book',
            field=models.BooleanField(default=False),
        ),
    ]
