# Generated by Django 4.1.6 on 2023-02-14 05:24

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0018_alter_person_account_type_alter_person_check_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.datetime_safe.datetime, null=True),
        ),
    ]
