# Generated by Django 4.1.6 on 2023-02-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0020_alter_person_dob_alter_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='----', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
