# Generated by Django 4.1.6 on 2023-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0022_alter_person_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='----', max_length=10),
        ),
    ]
