# Generated by Django 4.1.6 on 2023-02-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0023_person_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='account_type',
            field=models.CharField(choices=[('-----', '-----'), ('savings', 'Savings account'), ('current', 'Current account'), ('depoit', 'Depoit account'), ('demat', 'Demat account')], default='----', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('-----', '-----'), ('M', 'Male'), ('F', 'Female')], default='----', max_length=10),
        ),
        migrations.AlterModelTable(
            name='person',
            table=' credentials_person',
        ),
    ]
