# Generated by Django 4.1.6 on 2023-02-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0024_alter_person_account_type_alter_person_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.branch'),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credentials.district'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='person',
            table=None,
        ),
    ]
